version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:${TAG}
    container_name: ieelasticsearch
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    env_file:
      - ./env/.elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
   
  kibana:
    image: kibana:${TAG}
    container_name: iekibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch


volumes:
  elastic_data:
